{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ml-api.fullname" . }}
  labels:
    {{- include "ml-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
